### ISSUE TITLE
CompileSwift normal i386 errors when build phoneRTC Demo

### ISSUE THREAD

**Issue by ShongSu** [alongubkin/phonertc#169]
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal i386 /Users/Chen/Documents/Work/PhoneRTC/Code/Test/phonertc/demo/client/platforms/ios/Client/Plugins/com.dooble.phonertc/PhoneRTCPlugin.swift
	CompileSwift normal i386 /Users/Chen/Documents/Work/PhoneRTC/Code/Test/phonertc/demo/client/platforms/ios/Client/Plugins/com.dooble.phonertc/PCObserver.swift
	CompileSwift normal i386 /Users/Chen/Documents/Work/PhoneRTC/Code/Test/phonertc/demo/client/platforms/ios/Client/Plugins/com.dooble.phonertc/Session.swift
	CompileSwift normal i386 /Users/Chen/Documents/Work/PhoneRTC/Code/Test/phonertc/demo/client/platforms/ios/Client/Plugins/com.dooble.phonertc/Config.swift
	CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(5 failures)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Chen/Documents/Work/PhoneRTC/Code/Test/phonertc/demo/client/platforms/ios/cordova/build-debug.xcconfig,-project,Client.xcodeproj,ARCHS=i386,-target,Client,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Chen/Documents/Work/PhoneRTC/Code/Test/phonertc/demo/client/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Chen/Documents/Work/PhoneRTC/Code/Test/phonertc/demo/client/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/Chen/Documents/Work/PhoneRTC/Code/Test/phonertc/demo/client/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/Chen/Documents/Work/PhoneRTC/Code/Test/phonertc/demo/client/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by NekR** [comment]
Any ideas why this happens?

**Comment by heshamwatany** [comment]
in the project build setup change 
Enable Bitcode => NO

**Comment by vishal41190** [comment]
I am having the same issue:

The following build commands failed:
        CompileSwift normal i386 /Users/rocker/Documents/ocWebKings/swyk-client/platforms/ios/SWYK/Plugins/com.dooble.phonertc/PhoneRTCPlugin.swift
        CompileSwift normal i386 /Users/rocker/Documents/ocWebKings/swyk-client/platforms/ios/SWYK/Plugins/com.dooble.phonertc/PCObserver.swift
        CompileSwift normal i386 /Users/rocker/Documents/ocWebKings/swyk-client/platforms/ios/SWYK/Plugins/com.dooble.phonertc/Session.swift
        CompileSwift normal i386 /Users/rocker/Documents/ocWebKings/swyk-client/platforms/ios/SWYK/Plugins/com.dooble.phonertc/SessionDescriptionDelegate.swift
        CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(5 failures)
ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/rocker/Documents/ocWebKings/swyk-client/platforms/ios/cordova/build-debug.xcconfig,-project,SWYK.xcodeproj,ARCHS=i386,-target,SWYK,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/rocker/Documents/ocWebKings/swyk-client/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/rocker/Documents/ocWebKings/swyk-client/platforms/ios/build/sharedpch
You may not have the required environment or OS to build this project
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/rocker/Documents/ocWebKings/swyk-client/platforms/ios/cordova/build-debug.xcconfig,-project,SWYK.xcodeproj,ARCHS=i386,-target,SWYK,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/rocker/Documents/ocWebKings/swyk-client/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/rocker/Documents/ocWebKings/swyk-client/platforms/ios/build/sharedpch


How did you solved it?

**Comment by pengkobe** [comment]
same problem +1. you guys have any idea?
