### ISSUE TITLE
Video containers not visible on Android when using Crosswalk

### ISSUE THREAD

**Issue by Hyra** [alongubkin/phonertc#174]
Hi,

The plugin works perfectly on both iOS and Android, but after adding Crosswalk I can't see the video containers anymore. I do hear sound, and on the other client the video is being visible, just not on the phone.

I had the following error:

```E/AndroidRuntime(12487): java.lang.ClassCastException: org.crosswalk.engine.XWalkCordovaView cannot be cast to android.webkit.WebView
E/AndroidRuntime(12487):     at com.dooble.phonertc.PhoneRTCPlugin.createVideoView(PhoneRTCPlugin.java:320)
E/AndroidRuntime(12487):     at com.dooble.phonertc.PhoneRTCPlugin.refreshVideoView(PhoneRTCPlugin.java:345)
E/AndroidRuntime(12487):     at com.dooble.phonertc.PhoneRTCPlugin.addRemoteVideoTrack(PhoneRTCPlugin.java:292)
E/AndroidRuntime(12487):     at com.dooble.phonertc.Session$PCObserver$2.run(Session.java:283)
E/AndroidRuntime(12487):     at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime(12487):     at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(12487):     at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(12487):     at android.app.ActivityThread.main(ActivityThread.java:5283)
E/AndroidRuntime(12487):     at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12487):     at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(12487):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
E/AndroidRuntime(12487):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
E/AndroidRuntime(12487):     at dalvik.system.NativeStart.main(Native Method)```

So i replaced the (WebView) casts to XWalkView, but that doesnt help. Maybe it's being added outside the screen or under everything?

Anyone familiar with this?

**Comment by joseandresromero** [comment]
Did you find a solution for this issue? I have the same problem I after making some test I discovered that the video view is being added in the correct position but for some reason it is not visible. I tested setting a blue background to the video view and when I made a call the video view appears but only as a blue rectangle, without video.

**Comment by wtomsen** [comment]
VideoGLView.java
add code:
`
public VideoGLView(Context c, Point screenDimensions) {
	  super(c);
	  this.screenDimensions = screenDimensions;
	  setZOrderOnTop(true);  //bring to TOP
  }`
