### ISSUE TITLE
App Crash when start video

### ISSUE THREAD

**Issue by pavei** [alongubkin/phonertc#202]
When starting a chat i got this error. I dont know why. With Android 
 and Android 4.4.2.

When a look to AndroidManifest

```
    <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="23" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-feature android:glEsVersion="0x00020000" android:required="true" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
 
```
java.lang.SecurityException: ConnectivityService: Neither user 10159 nor current process has android.permission.ACCESS_NETWORK_STATE.
06-04 17:30:28.705  13586-13922/com.dooble.phonertc.demo.app W/System.err﹕ at android.os.Parcel.readException(Parcel.java:1465)
06-04 17:30:28.705  13586-13922/com.dooble.phonertc.demo.app W/System.err﹕ at android.os.Parcel.readException(Parcel.java:1419)
06-04 17:30:28.705  13586-13922/com.dooble.phonertc.demo.app W/System.err﹕ at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1139)
06-04 17:30:28.705  13586-13922/com.dooble.phonertc.demo.app W/System.err﹕ at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:691)
06-04 17:30:28.705  13586-13922/com.dooble.phonertc.demo.app W/System.err﹕ at org.webrtc.NetworkMonitorAutoDetect$ConnectivityManagerDelegate.getNetworkState(NetworkMonitorAutoDetect.java:191)
06-04 17:30:28.705  13586-13922/com.dooble.phonertc.demo.app W/System.err﹕ at org.webrtc.NetworkMonitorAutoDetect.<init>(NetworkMonitorAutoDetect.java:441)
06-04 17:30:28.705  13586-13922/com.dooble.phonertc.demo.app W/System.err﹕ at org.webrtc.NetworkMonitor.setAutoDetectConnectivityStateInternal(NetworkMonitor.java:139)
06-04 17:30:28.705  13586-13922/com.dooble.phonertc.demo.app W/System.err﹕ at org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:108)
06-04 17:30:28.705  13586-13922/com.dooble.phonertc.demo.app W/System.err﹕ at dalvik.system.NativeStart.run(Native Method)
06-04 17:30:28.705  13586-13922/com.dooble.phonertc.demo.app E/rtc﹕ #
    # Fatal error in ../../webrtc/api/java/jni/androidnetworkmonitor_jni.cc, line 195
    # Check failed: !jni()->ExceptionCheck()
    # Error during CallVoidMethod
    #
06-04 17:30:28.705  13586-13922/com.dooble.phonertc.demo.app A/libc﹕ Fatal signal 6 (SIGABRT) at 0x00003512 (code=-6), thread 13922 (worker_thread)

**Comment by Mgonand** [comment]
Take a look here: http://stackoverflow.com/a/27745226/3114308

Let me know if it works for you.
