### ISSUE TITLE
64bit +  Fresco  couldn't find "libjingle_peerconnection_so.so"

### ISSUE THREAD

**Issue by CShame** [alongubkin/phonertc#212]
"nativeLibraryDirectories=[/data/app/com.lukouapp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libjingle_peerconnection_so.so"

**Comment by zengchuan** [comment]
I got the same error:

08-19 12:53:42.964 E/AndroidRuntime(11476): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/zengchuan.nancaochang.com-1/base.apk"],nativeLibraryDirectories=[/data/app/zengchuan.nancaochang.com-1/lib/arm64, /system/fake-libs64, /data/app/zengchuan.nancaochang.com-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libjingle_peerconnection_so.so"
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at java.lang.Runtime.loadLibrary0(Runtime.java:972)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at java.lang.System.loadLibrary(System.java:1530)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at org.webrtc.PeerConnectionFactory.<clinit>(PeerConnectionFactory.java:22)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at org.webrtc.PeerConnectionFactory.initializeAndroidGlobals(Native Method)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at com.dooble.phonertc.PhoneRTCPlugin$1.run(PhoneRTCPlugin.java:81)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at android.os.Handler.handleCallback(Handler.java:751)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at android.os.Looper.loop(Looper.java:154)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at android.app.ActivityThread.main(ActivityThread.java:6114)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at java.lang.reflect.Method.invoke(Native Method)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
08-19 12:53:42.979 W/ActivityManager( 2030):   Force finishing activity zengchuan.nancaochang.com/.MainActivity
