### ISSUE TITLE
Crashes in android during the session constructor initialisation

### ISSUE THREAD

**Issue by balaabhinav** [alongubkin/phonertc#228]
Hi,

My android phones (moto x2, xiomi mi3, OnePlus) all of them crash when in the line making a call to the session constructor. I saw that a similar issue was closed last year. I have followed the documentation and the sample ionic code to create my Ionic2 version for video calling. Could anyone help me out if I am missing something?

**Comment by zengchuan** [comment]
do you solve it? I have the same error. When new cordova.plugins.phonertc.Session(config); it crash! browser(change password to credential) is right but android is wrong.

**Comment by balaabhinav** [comment]
Nope, I was not able to solve it. I just started using a third party video calling app and invoking it from my ionic app.


________________________________

**Comment by chetanbnaik** [comment]
try giving the permissions ACCESS_NETWORK_STATE if not already.

**Comment by zengchuan** [comment]
08-19 12:53:42.964 E/AndroidRuntime(11476): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/zengchuan.nancaochang.com-1/base.apk"],nativeLibraryDirectories=[/data/app/zengchuan.nancaochang.com-1/lib/arm64, /system/fake-libs64, /data/app/zengchuan.nancaochang.com-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libjingle_peerconnection_so.so"
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at java.lang.Runtime.loadLibrary0(Runtime.java:972)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at java.lang.System.loadLibrary(System.java:1530)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at org.webrtc.PeerConnectionFactory.<clinit>(PeerConnectionFactory.java:22)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at org.webrtc.PeerConnectionFactory.initializeAndroidGlobals(Native Method)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at com.dooble.phonertc.PhoneRTCPlugin$1.run(PhoneRTCPlugin.java:81)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at android.os.Handler.handleCallback(Handler.java:751)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at android.os.Looper.loop(Looper.java:154)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at android.app.ActivityThread.main(ActivityThread.java:6114)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at java.lang.reflect.Method.invoke(Native Method)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
08-19 12:53:42.964 E/AndroidRuntime(11476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
08-19 12:53:42.979 W/ActivityManager( 2030):   Force finishing activity zengchuan.nancaochang.com/.MainActivity

how to resolve it?
