### ISSUE TITLE
org.crosswalk.engine.XWalkCordovaView cannot be cast to android.webkit.WebView

### ISSUE THREAD

**Issue by MeAntonio** [alongubkin/phonertc#240]
Have installed crosswalk 2.3.0 into my cordova app and app started exiting when trying to establish p2p connection with a user in game. This is the logger error:

FATAL EXCEPTION: main
E/AndroidRuntime(  794): Process: hr.something.something, PID: 794
E/AndroidRuntime(  794): java.lang.ClassCastException: org.crosswalk.engine.XWalkCordovaView cannot be cast to android.webkit.WebView
E/AndroidRuntime(  794):        at com.dooble.phonertc.PhoneRTCPlugin.createVideoView(PhoneRTCPlugin.java:388)
E/AndroidRuntime(  794):        at com.dooble.phonertc.PhoneRTCPlugin.refreshVideoView(PhoneRTCPlugin.java:419)
E/AndroidRuntime(  794):        at com.dooble.phonertc.PhoneRTCPlugin.addRemoteVideoTrack(PhoneRTCPlugin.java:343)
E/AndroidRuntime(  794):        at com.dooble.phonertc.Session$PCObserver$2.run(Session.java:284)
E/AndroidRuntime(  794):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(  794):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(  794):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(  794):        at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime(  794):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  794):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(  794):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime(  794):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
E/AndroidRuntime(  794):        at dalvik.system.NativeStart.main(Native Method)

If someone know how to approach this error please help.

**Comment by Tonchyk** [comment]
Here is the solution:

https://github.com/Tonchyk/phonertc

It works all fine with crosswalk but doesn't check if there is crosswalk installed so it doesn't yet work for no crosswalk use.
